### ISSUE TITLE
Sample site code?

### ISSUE THREAD

**Issue by crazy4groovy** [jlxw/static-json-db#1]
Is the sample site code available for www.playliststar.com ?

I'm still not quite sure how I would run this on the backend of say, netlify, and still call it from my front end code. A few more instructions may help. Looks cool - Thanks!

**Comment by jlxw** [comment]
Thanks for checking this out!

Try looking at the html example here:
https://jlxw.github.io/static-json-db/example.html

**Comment by crazy4groovy** [comment]
OK, I get how I can run it from the browser side.

But I'm still confused about how to run this backend on a JAM stack.

(That page is obviously hosted by Github Pages, but I don't see it listed anywhere in the gh repo, in any branches or tags... 🤷)

**Comment by jlxw** [comment]
The Github Pages are in /docs :)

You'd still need Node to write to the database, then expose it via http or deploy it as a static site to be read by the browser.

I'll update the README to try and make this clearer.

**Comment by crazy4groovy** [comment]
Ah I understand a little bit better now.

The database is populated/written at deploy-time. It is read-only in the browser. I wondered if the browser could write data, too.

**Comment by jlxw** [comment]
You would need to expose your own API to it to write data, handle its own authentication/security/etc
